### ISSUE TITLE
Website not sized to viewport on mobile

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/website#6]
Is currently by default:
![WhatsApp Image 2019-05-19 at 01 27 20](https://user-images.githubusercontent.com/1184274/57976365-e5171180-79d5-11e9-87e9-2a6022c00ea7.jpeg)

Should be:
![WhatsApp Image 2019-05-19 at 01 26 58](https://user-images.githubusercontent.com/1184274/57976364-ce70ba80-79d5-11e9-96cf-56f72dfbc0ad.jpeg)

**Comment by Harjot1Singh** [comment]
No idea what it is, it's not the `<meta viewport>` tag

**Comment by Harjot1Singh** [comment]
It appears that opening the site and rotating it into landscape and back fixes it... or setting the `initial-viewport=0.5` (but this breaks landscape)

**Comment by bhajneet** [comment]
Should be fixed now
